# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QBrush, QPixmap


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1441, 814)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/20200316130516.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("./icon/20200316155650.png")))
        self.setPalette(palette)
        self.load_dataset_start = QtWidgets.QPushButton(Form)
        self.load_dataset_start.setGeometry(QtCore.QRect(610, 230, 171, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.load_dataset_start.setFont(font)
        self.load_dataset_start.setStyleSheet("QPushButton{border-image: url(:/icon/20200316135232.png);}\n"
"QPushButton:hover{border-image: url(:/icon/button.png);}")
        self.load_dataset_start.setObjectName("load_dataset_start")
        self.load_dataset = QtWidgets.QLabel(Form)
        self.load_dataset.setGeometry(QtCore.QRect(10, 190, 311, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.load_dataset.setFont(font)
        self.load_dataset.setAlignment(QtCore.Qt.AlignCenter)
        self.load_dataset.setObjectName("load_dataset")
        self.load_dataset_filepath = QtWidgets.QLineEdit(Form)
        self.load_dataset_filepath.setGeometry(QtCore.QRect(330, 190, 521, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.load_dataset_filepath.setFont(font)
        self.load_dataset_filepath.setAlignment(QtCore.Qt.AlignCenter)
        self.load_dataset_filepath.setObjectName("load_dataset_filepath")
        self.load_dataset_file = QtWidgets.QPushButton(Form)
        self.load_dataset_file.setGeometry(QtCore.QRect(390, 230, 171, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.load_dataset_file.setFont(font)
        self.load_dataset_file.setStyleSheet("QPushButton{border-image: url(:/icon/20200316135232.png);}\n"
"QPushButton:hover{border-image: url(:/icon/button.png);}")
        self.load_dataset_file.setObjectName("load_dataset_file")
        self.risk_prob = QtWidgets.QLabel(Form)
        self.risk_prob.setGeometry(QtCore.QRect(70, 300, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.risk_prob.setFont(font)
        self.risk_prob.setAlignment(QtCore.Qt.AlignCenter)
        self.risk_prob.setObjectName("risk_prob")
        self.risk_prob_show = QtWidgets.QLineEdit(Form)
        self.risk_prob_show.setGeometry(QtCore.QRect(330, 300, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.risk_prob_show.setFont(font)
        self.risk_prob_show.setAlignment(QtCore.Qt.AlignCenter)
        self.risk_prob_show.setObjectName("risk_prob_show")
        self.risk_traj = QtWidgets.QLabel(Form)
        self.risk_traj.setGeometry(QtCore.QRect(70, 340, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.risk_traj.setFont(font)
        self.risk_traj.setAlignment(QtCore.Qt.AlignCenter)
        self.risk_traj.setObjectName("risk_traj")
        self.load_dataset_2 = QtWidgets.QLabel(Form)
        self.load_dataset_2.setGeometry(QtCore.QRect(50, 150, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.load_dataset_2.setFont(font)
        self.load_dataset_2.setAlignment(QtCore.Qt.AlignCenter)
        self.load_dataset_2.setObjectName("load_dataset_2")
        self.notice_txt = QtWidgets.QLineEdit(Form)
        self.notice_txt.setGeometry(QtCore.QRect(330, 150, 521, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.notice_txt.setFont(font)
        self.notice_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.notice_txt.setObjectName("notice_txt")
        self.jdk_path = QtWidgets.QLineEdit(Form)
        self.jdk_path.setGeometry(QtCore.QRect(330, 110, 521, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.jdk_path.setFont(font)
        self.jdk_path.setStyleSheet("")
        self.jdk_path.setAlignment(QtCore.Qt.AlignCenter)
        self.jdk_path.setObjectName("jdk_path")
        self.load_jdk = QtWidgets.QLabel(Form)
        self.load_jdk.setGeometry(QtCore.QRect(70, 110, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.load_jdk.setFont(font)
        self.load_jdk.setAlignment(QtCore.Qt.AlignCenter)
        self.load_jdk.setObjectName("load_jdk")
        self.load_test_2 = QtWidgets.QLabel(Form)
        self.load_test_2.setGeometry(QtCore.QRect(300, 340, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_2.setFont(font)
        self.load_test_2.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_2.setObjectName("load_test_2")
        self.load_test_3 = QtWidgets.QLabel(Form)
        self.load_test_3.setGeometry(QtCore.QRect(530, 340, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_3.setFont(font)
        self.load_test_3.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_3.setObjectName("load_test_3")
        self.load_test_4 = QtWidgets.QLabel(Form)
        self.load_test_4.setGeometry(QtCore.QRect(980, 340, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_4.setFont(font)
        self.load_test_4.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_4.setObjectName("load_test_4")
        self.a1 = QtWidgets.QLineEdit(Form)
        self.a1.setGeometry(QtCore.QRect(330, 380, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.a1.setFont(font)
        self.a1.setText("")
        self.a1.setAlignment(QtCore.Qt.AlignCenter)
        self.a1.setObjectName("a1")
        self.c1 = QtWidgets.QLineEdit(Form)
        self.c1.setGeometry(QtCore.QRect(490, 380, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.c1.setFont(font)
        self.c1.setText("")
        self.c1.setAlignment(QtCore.Qt.AlignCenter)
        self.c1.setObjectName("c1")
        self.d1 = QtWidgets.QLineEdit(Form)
        self.d1.setGeometry(QtCore.QRect(680, 380, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.d1.setFont(font)
        self.d1.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.d1.setText("")
        self.d1.setAlignment(QtCore.Qt.AlignCenter)
        self.d1.setObjectName("d1")
        self.c2 = QtWidgets.QLineEdit(Form)
        self.c2.setGeometry(QtCore.QRect(490, 460, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.c2.setFont(font)
        self.c2.setText("")
        self.c2.setAlignment(QtCore.Qt.AlignCenter)
        self.c2.setObjectName("c2")
        self.d2 = QtWidgets.QLineEdit(Form)
        self.d2.setGeometry(QtCore.QRect(680, 460, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.d2.setFont(font)
        self.d2.setText("")
        self.d2.setAlignment(QtCore.Qt.AlignCenter)
        self.d2.setObjectName("d2")
        self.a2 = QtWidgets.QLineEdit(Form)
        self.a2.setGeometry(QtCore.QRect(330, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.a2.setFont(font)
        self.a2.setText("")
        self.a2.setAlignment(QtCore.Qt.AlignCenter)
        self.a2.setObjectName("a2")
        self.c3 = QtWidgets.QLineEdit(Form)
        self.c3.setGeometry(QtCore.QRect(490, 540, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.c3.setFont(font)
        self.c3.setText("")
        self.c3.setAlignment(QtCore.Qt.AlignCenter)
        self.c3.setObjectName("c3")
        self.d3 = QtWidgets.QLineEdit(Form)
        self.d3.setGeometry(QtCore.QRect(680, 540, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.d3.setFont(font)
        self.d3.setText("")
        self.d3.setAlignment(QtCore.Qt.AlignCenter)
        self.d3.setObjectName("d3")
        self.a3 = QtWidgets.QLineEdit(Form)
        self.a3.setGeometry(QtCore.QRect(330, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.a3.setFont(font)
        self.a3.setText("")
        self.a3.setAlignment(QtCore.Qt.AlignCenter)
        self.a3.setObjectName("a3")
        self.c4 = QtWidgets.QLineEdit(Form)
        self.c4.setGeometry(QtCore.QRect(490, 620, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.c4.setFont(font)
        self.c4.setText("")
        self.c4.setAlignment(QtCore.Qt.AlignCenter)
        self.c4.setObjectName("c4")
        self.d4 = QtWidgets.QLineEdit(Form)
        self.d4.setGeometry(QtCore.QRect(680, 620, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.d4.setFont(font)
        self.d4.setText("")
        self.d4.setAlignment(QtCore.Qt.AlignCenter)
        self.d4.setObjectName("d4")
        self.a4 = QtWidgets.QLineEdit(Form)
        self.a4.setGeometry(QtCore.QRect(330, 620, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.a4.setFont(font)
        self.a4.setText("")
        self.a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a4.setObjectName("a4")
        self.c5 = QtWidgets.QLineEdit(Form)
        self.c5.setGeometry(QtCore.QRect(490, 700, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.c5.setFont(font)
        self.c5.setText("")
        self.c5.setAlignment(QtCore.Qt.AlignCenter)
        self.c5.setObjectName("c5")
        self.d5 = QtWidgets.QLineEdit(Form)
        self.d5.setGeometry(QtCore.QRect(680, 700, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.d5.setFont(font)
        self.d5.setText("")
        self.d5.setAlignment(QtCore.Qt.AlignCenter)
        self.d5.setObjectName("d5")
        self.a5 = QtWidgets.QLineEdit(Form)
        self.a5.setGeometry(QtCore.QRect(330, 700, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.a5.setFont(font)
        self.a5.setText("")
        self.a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a5.setObjectName("a5")
        self.load_test_6 = QtWidgets.QLabel(Form)
        self.load_test_6.setGeometry(QtCore.QRect(250, 380, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_6.setFont(font)
        self.load_test_6.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_6.setObjectName("load_test_6")
        self.load_test_7 = QtWidgets.QLabel(Form)
        self.load_test_7.setGeometry(QtCore.QRect(250, 460, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_7.setFont(font)
        self.load_test_7.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_7.setObjectName("load_test_7")
        self.load_test_8 = QtWidgets.QLabel(Form)
        self.load_test_8.setGeometry(QtCore.QRect(250, 540, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_8.setFont(font)
        self.load_test_8.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_8.setObjectName("load_test_8")
        self.load_test_9 = QtWidgets.QLabel(Form)
        self.load_test_9.setGeometry(QtCore.QRect(250, 620, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_9.setFont(font)
        self.load_test_9.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_9.setObjectName("load_test_9")
        self.load_test_10 = QtWidgets.QLabel(Form)
        self.load_test_10.setGeometry(QtCore.QRect(250, 700, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_10.setFont(font)
        self.load_test_10.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_10.setObjectName("load_test_10")
        self.load_jdk_2 = QtWidgets.QLabel(Form)
        self.load_jdk_2.setGeometry(QtCore.QRect(160, 20, 681, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.load_jdk_2.setFont(font)
        self.load_jdk_2.setAlignment(QtCore.Qt.AlignCenter)
        self.load_jdk_2.setObjectName("load_jdk_2")
        self.b3 = QtWidgets.QLineEdit(Form)
        self.b3.setGeometry(QtCore.QRect(410, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.b3.setFont(font)
        self.b3.setText("")
        self.b3.setAlignment(QtCore.Qt.AlignCenter)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QLineEdit(Form)
        self.b4.setGeometry(QtCore.QRect(410, 620, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.b4.setFont(font)
        self.b4.setText("")
        self.b4.setAlignment(QtCore.Qt.AlignCenter)
        self.b4.setObjectName("b4")
        self.b1 = QtWidgets.QLineEdit(Form)
        self.b1.setGeometry(QtCore.QRect(410, 380, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.b1.setFont(font)
        self.b1.setText("")
        self.b1.setAlignment(QtCore.Qt.AlignCenter)
        self.b1.setObjectName("b1")
        self.b5 = QtWidgets.QLineEdit(Form)
        self.b5.setGeometry(QtCore.QRect(410, 700, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.b5.setFont(font)
        self.b5.setText("")
        self.b5.setAlignment(QtCore.Qt.AlignCenter)
        self.b5.setObjectName("b5")
        self.load_test_5 = QtWidgets.QLabel(Form)
        self.load_test_5.setGeometry(QtCore.QRect(380, 340, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_5.setFont(font)
        self.load_test_5.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_5.setObjectName("load_test_5")
        self.b2 = QtWidgets.QLineEdit(Form)
        self.b2.setGeometry(QtCore.QRect(410, 460, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.b2.setFont(font)
        self.b2.setText("")
        self.b2.setAlignment(QtCore.Qt.AlignCenter)
        self.b2.setObjectName("b2")
        self.e1 = QtWidgets.QLineEdit(Form)
        self.e1.setGeometry(QtCore.QRect(490, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.e1.setFont(font)
        self.e1.setText("")
        self.e1.setAlignment(QtCore.Qt.AlignCenter)
        self.e1.setObjectName("e1")
        self.f1 = QtWidgets.QLineEdit(Form)
        self.f1.setGeometry(QtCore.QRect(680, 420, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.f1.setFont(font)
        self.f1.setText("")
        self.f1.setAlignment(QtCore.Qt.AlignCenter)
        self.f1.setObjectName("f1")
        self.load_test_12 = QtWidgets.QLabel(Form)
        self.load_test_12.setGeometry(QtCore.QRect(330, 425, 131, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_12.setFont(font)
        self.load_test_12.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_12.setObjectName("load_test_12")
        self.load_test_13 = QtWidgets.QLabel(Form)
        self.load_test_13.setGeometry(QtCore.QRect(330, 505, 131, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_13.setFont(font)
        self.load_test_13.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_13.setObjectName("load_test_13")
        self.f2 = QtWidgets.QLineEdit(Form)
        self.f2.setGeometry(QtCore.QRect(680, 500, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.f2.setFont(font)
        self.f2.setText("")
        self.f2.setAlignment(QtCore.Qt.AlignCenter)
        self.f2.setObjectName("f2")
        self.e2 = QtWidgets.QLineEdit(Form)
        self.e2.setGeometry(QtCore.QRect(490, 500, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.e2.setFont(font)
        self.e2.setText("")
        self.e2.setAlignment(QtCore.Qt.AlignCenter)
        self.e2.setObjectName("e2")
        self.e3 = QtWidgets.QLineEdit(Form)
        self.e3.setGeometry(QtCore.QRect(490, 580, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.e3.setFont(font)
        self.e3.setText("")
        self.e3.setAlignment(QtCore.Qt.AlignCenter)
        self.e3.setObjectName("e3")
        self.f3 = QtWidgets.QLineEdit(Form)
        self.f3.setGeometry(QtCore.QRect(680, 580, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.f3.setFont(font)
        self.f3.setText("")
        self.f3.setAlignment(QtCore.Qt.AlignCenter)
        self.f3.setObjectName("f3")
        self.load_test_14 = QtWidgets.QLabel(Form)
        self.load_test_14.setGeometry(QtCore.QRect(330, 585, 131, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_14.setFont(font)
        self.load_test_14.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_14.setObjectName("load_test_14")
        self.e4 = QtWidgets.QLineEdit(Form)
        self.e4.setGeometry(QtCore.QRect(490, 660, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.e4.setFont(font)
        self.e4.setText("")
        self.e4.setAlignment(QtCore.Qt.AlignCenter)
        self.e4.setObjectName("e4")
        self.load_test_15 = QtWidgets.QLabel(Form)
        self.load_test_15.setGeometry(QtCore.QRect(330, 665, 131, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_15.setFont(font)
        self.load_test_15.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_15.setObjectName("load_test_15")
        self.f4 = QtWidgets.QLineEdit(Form)
        self.f4.setGeometry(QtCore.QRect(680, 660, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.f4.setFont(font)
        self.f4.setText("")
        self.f4.setAlignment(QtCore.Qt.AlignCenter)
        self.f4.setObjectName("f4")
        self.e5 = QtWidgets.QLineEdit(Form)
        self.e5.setGeometry(QtCore.QRect(490, 740, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.e5.setFont(font)
        self.e5.setText("")
        self.e5.setAlignment(QtCore.Qt.AlignCenter)
        self.e5.setObjectName("e5")
        self.load_test_16 = QtWidgets.QLabel(Form)
        self.load_test_16.setGeometry(QtCore.QRect(330, 745, 131, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_16.setFont(font)
        self.load_test_16.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_16.setObjectName("load_test_16")
        self.f5 = QtWidgets.QLineEdit(Form)
        self.f5.setGeometry(QtCore.QRect(680, 740, 731, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.f5.setFont(font)
        self.f5.setText("")
        self.f5.setAlignment(QtCore.Qt.AlignCenter)
        self.f5.setObjectName("f5")
        self.test_traj_input = QtWidgets.QTextEdit(Form)
        self.test_traj_input.setGeometry(QtCore.QRect(890, 110, 521, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.test_traj_input.setFont(font)
        self.test_traj_input.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.test_traj_input.setObjectName("test_traj_input")
        self.load_test_11 = QtWidgets.QLabel(Form)
        self.load_test_11.setGeometry(QtCore.QRect(890, 70, 521, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_11.setFont(font)
        self.load_test_11.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test_11.setObjectName("load_test_11")
        self.load_test_button = QtWidgets.QPushButton(Form)
        self.load_test_button.setGeometry(QtCore.QRect(1000, 230, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.load_test_button.setFont(font)
        self.load_test_button.setMouseTracking(False)
        self.load_test_button.setStyleSheet("QPushButton{border-image: url(:/icon/20200316135232.png);}\n"
"QPushButton:hover{border-image: url(:/icon/button.png);}")
        self.load_test_button.setObjectName("load_test_button")
        self.clear_button = QtWidgets.QPushButton(Form)
        self.clear_button.setGeometry(QtCore.QRect(1180, 230, 121, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton{border-image: url(:/icon/20200316135232.png);}\n"
"QPushButton:hover{border-image: url(:/icon/button.png);}")
        self.clear_button.setObjectName("clear_button")
        self.load_test = QtWidgets.QLabel(Form)
        self.load_test.setGeometry(QtCore.QRect(950, 40, 361, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load_test.setFont(font)
        self.load_test.setAlignment(QtCore.Qt.AlignCenter)
        self.load_test.setObjectName("load_test")
        self.risk_prob_2 = QtWidgets.QLabel(Form)
        self.risk_prob_2.setGeometry(QtCore.QRect(450, 300, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.risk_prob_2.setFont(font)
        self.risk_prob_2.setAlignment(QtCore.Qt.AlignCenter)
        self.risk_prob_2.setObjectName("risk_prob_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(620, 290, 71, 61))
        self.label.setStyleSheet("image: url(:/icon/20200316155853.png);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Potential Risk Infector Mining System "))
        self.load_dataset_start.setText(_translate("Form", "Load database"))
        self.load_dataset.setText(_translate("Form", "Confirmed patient database path"))
        self.load_dataset_file.setText(_translate("Form", "Select DB path"))
        self.risk_prob.setText(_translate("Form", "Risk of infection"))
        self.risk_traj.setText(_translate("Form", "Risk trajectory"))
        self.load_dataset_2.setText(_translate("Form", "Current running status"))
        self.load_jdk.setText(_translate("Form", "JDK path"))
        self.load_test_2.setText(_translate("Form", "Risk"))
        self.load_test_3.setText(_translate("Form", "Time"))
        self.load_test_4.setText(_translate("Form", "Space trajectory"))
        self.load_test_6.setText(_translate("Form", "Top-1"))
        self.load_test_7.setText(_translate("Form", "Top-2"))
        self.load_test_8.setText(_translate("Form", "Top-3"))
        self.load_test_9.setText(_translate("Form", "Top-4"))
        self.load_test_10.setText(_translate("Form", "Top-5"))
        self.load_jdk_2.setText(_translate("Form", "Potential Risk Infector Mining System"))
        self.load_test_5.setText(_translate("Form", "Patient"))
        self.load_test_12.setText(_translate("Form", "Test sample"))
        self.load_test_13.setText(_translate("Form", "Test sample"))
        self.load_test_14.setText(_translate("Form", "Test sample"))
        self.load_test_15.setText(_translate("Form", "Test sample"))
        self.load_test_16.setText(_translate("Form", "Test sample"))
        self.load_test_11.setText(_translate("Form", "Example: Tra-num Start-loc M.D.H End-loc M.D.H"))
        self.load_test_button.setText(_translate("Form", "Submit"))
        self.clear_button.setText(_translate("Form", "Clear all"))
        self.load_test.setText(_translate("Form", "Please enter the test trajectory"))
        self.risk_prob_2.setText(_translate("Form", "Risk warning"))
import pic_rc
